### ISSUE TITLE
Question on Setup Descriptors

### ISSUE THREAD

**Issue by warrench** [zhinst/laboneq#20]
For setting up a device in our lab we tend to name things in terms of qubits and couplers as we do not drive two qubit gates directly using the qubits. Instead we use these intermediate elements.

If I were to set a descriptor for one of my hdawgs as follows, does the inclusion of a `cx/flux_line` mess with the name space? I.e is everything for LabOneQ dependent on the label parsing a `qx` value or is the name just an identifier which can be handled internally by the API and I can distinguish based on `c` labels and `q` labels?

```
device_hdawg2:
    - iq_signal: q5/drive_line
      ports: [SIGOUTS/4, SIGOUTS/5]     
    - iq_signal: q5/drive_line_ef
      ports: [SIGOUTS/4, SIGOUTS/5]    
    - rf_signal: c1/flux_line
      ports: [SIGOUTS/0]
    - rf_signal: c2/flux_line
      ports: [SIGOUTS/1]
    - rf_signal: c3/flux_line
      ports: [SIGOUTS/2] 
    - rf_signal: c4/flux_line
      ports: [SIGOUTS/3] 
```
